# Generated by Django 4.2.1 on 2025-07-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0008_husband_women_husband'),
    ]

    operations = [
        migrations.RenameField(
            model_name='husband',
            old_name='afe',
            new_name='age',
        ),
    ]
