# Generated by Django 5.2.4 on 2025-08-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0012_women_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['id'], 'verbose_name': 'Women', 'verbose_name_plural': 'Womenshy'},
        ),
        migrations.RemoveIndex(
            model_name='women',
            name='women_women_time_cr_9f33c2_idx',
        ),
        migrations.AddIndex(
            model_name='women',
            index=models.Index(fields=['id'], name='women_women_id_9b7715_idx'),
        ),
    ]
