# Generated by Django 5.2.4 on 2025-08-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0014_alter_women_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['-time_create'], 'verbose_name': 'Women', 'verbose_name_plural': 'Womenshy'},
        ),
        migrations.RemoveIndex(
            model_name='women',
            name='women_women_time_cr_21b781_idx',
        ),
        migrations.AddIndex(
            model_name='women',
            index=models.Index(fields=['-time_create'], name='women_women_time_cr_9f33c2_idx'),
        ),
    ]
